spring.application.name=patronika

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=12

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

ws.url=${WS_URL}
ws.username=${WS_USERNAME}
ws.password=${WS_PASSWORD}
ws.action=${WS_ACTION}

rate-limit.enabled=true
rate-limit.cache.maximum-size=50000
rate-limit.cache.expire-after-access=PT30M

# Configuración SMTP2GO
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT:2025}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}

# Protocolo y seguridad
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true